# coding: utf-8

from __future__ import absolute_import

from utils.consts import (
    SUBJECT_MATH,
    SUBJECT_PHYSICS,
    SUBJECT_CHEMISTRY,
    SUBJECT_BIOLOGY
)

subject_name2id = {
    'math': SUBJECT_MATH,
    'physics': SUBJECT_PHYSICS,
    'chemistry': SUBJECT_CHEMISTRY,
    'biology': SUBJECT_BIOLOGY
}

SCIENCE_CONSTS = {
    # math model
    'K_MATH_CHOICE': 2000,
    'K_MATH_CHOICE_ANALYSIS': 2001,

    'K_MATH_BLANK': 2002,
    'K_MATH_BLANK_QUESTION': 2003,
    'K_MATH_BLANK_ANALYSIS': 2004,

    'K_MATH_RESPONSE': 2006,
    'K_MATH_RESPONSE_QUESTION': 2007,
    'K_MATH_RESPONSE_ANALYSIS': 2008,

    # biology model
    'K_BIOLOGY_CHOICE': 7000,
    'K_BIOLOGY_CHOICE_ANALYSIS': 7002,

    'K_BIOLOGY_BLANK': 7010,
    'K_BIOLOGY_BLANK_QUESTION': 7011,
    'K_BIOLOGY_BLANK_ANALYSIS': 7013,

    'K_BIOLOGY_RESPONSE': 7020,
    'K_BIOLOGY_RESPONSE_QUESTION': 7021,
    'K_BIOLOGY_RESPONSE_ANALYSIS': 7023,

    # chemistry model
    'K_CHEMISTRY_CHOICE': 7100,
    'K_CHEMISTRY_CHOICE_ANALYSIS': 7102,

    'K_CHEMISTRY_BLANK': 7110,
    'K_CHEMISTRY_BLANK_QUESTION': 7111,
    'K_CHEMISTRY_BLANK_ANALYSIS': 7113,

    'K_CHEMISTRY_RESPONSE': 7120,
    'K_CHEMISTRY_RESPONSE_QUESTION': 7121,
    'K_CHEMISTRY_RESPONSE_ANALYSIS': 7123,

    # physics model
    'K_PHYSICS_CHOICE': 7200,
    'K_PHYSICS_CHOICE_ANALYSIS': 7202,

    'K_PHYSICS_BLANK': 7210,
    'K_PHYSICS_BLANK_QUESTION': 7211,
    'K_PHYSICS_BLANK_ANALYSIS': 7213,

    'K_PHYSICS_RESPONSE': 7220,
    'K_PHYSICS_RESPONSE_QUESTION': 7221,
    'K_PHYSICS_RESPONSE_ANALYSIS': 7223
}


QUESTION_TYPE_PRACTICE = 1 # 练题
QUESTION_TYPE_CHALLENGE = 2 # 挑战
QUESTION_TYPE_REVIEW = 3 # 查看

